initial commit: Sprint13
emtpy61/java-shareit pull request #1
Opened 2023-07-22 16:16 UTC by emtpy61

Sprint13

2023-07-23 07:19 UTC, alexache requested changes

2023-07-23 07:19 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/mapper/ItemMapper.java
> +                .owner(itemDto.getOwnerId() != null ? User.builder().id(itemDto.getOwnerId()).build() : null)
Это не совсем правильно. Нужно запрашивать полноценный объект User у репозитория юзеров по айди, и передавать в маппер или отдельно выставлять

2023-07-23 07:19 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    private final UserService userService;
Лучше работать с другими репозиториями, чем с сервисами, не будет лишних конвертация в ДТО из ДТО

2023-07-23 07:19 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +                .owner(UserMapper.fromUserDto(userService.getUserById(ownerId)))
Как например здесь излишне в ДТО, потом из ДТО

2023-07-23 07:19 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        return itemRepository.findAll().stream()
Полный скан по списку не самый лучший способ, было бы лучше иметь отдельную мапу юзера на список его вещей

2023-07-23 07:19 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        return itemRepository.findAll().stream()
Это логичнее было бы иметь в репозитории, нежели сервисе

2023-07-23 07:19 UTC, alexache commented on src/main/java/ru/practicum/shareit/request/dto/ItemRequestDto.java
> +    private Integer requestId;
А что это за айди?

2023-07-23 07:19 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +    @NotNull(message = "не может быть пустым.")
Для чего валидации в модели?

2023-07-23 07:19 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/repository/UserRepositoryImpl.java
> +        return entities.values().stream()
Полный обход по списку пользователей не самый лучший способ, лучше бы завести отдельный хешсет для хранения имейлов, тогда такой поиск будет намного быстрее

2023-07-23 08:09 UTC, emtpy61 commented on src/main/java/ru/practicum/shareit/item/mapper/ItemMapper.java
> +                .owner(itemDto.getOwnerId() != null ? User.builder().id(itemDto.getOwnerId()).build() : null)
Передал в маппер

2023-07-23 08:09 UTC, emtpy61 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    private final UserService userService;
Поправил

2023-07-23 08:10 UTC, emtpy61 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +                .owner(UserMapper.fromUserDto(userService.getUserById(ownerId)))
Исправил. Но, как по мне, выглядит некрасиво.

2023-07-23 08:13 UTC, emtpy61 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        return itemRepository.findAll().stream()
Тоже об этом думал. Но не вижу смысла городить доп мапы при искусственной замены БД. Где эта проблема решается SQL запросом. Тем более все это будет выкинуто в следующем спринте.

2023-07-23 08:18 UTC, emtpy61 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        return itemRepository.findAll().stream()
Перенес

2023-07-23 08:22 UTC, emtpy61 commented on src/main/java/ru/practicum/shareit/request/dto/ItemRequestDto.java
> +    private Integer requestId;
Поправил

2023-07-23 08:22 UTC, emtpy61 commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +    @NotNull(message = "не может быть пустым.")
Убрал

2023-07-23 08:27 UTC, emtpy61 commented on src/main/java/ru/practicum/shareit/user/repository/UserRepositoryImpl.java
> +        return entities.values().stream()
Тоже не вижу смыла. Данные наработки удалятся в следующих спринтах. @UniqueConstraint и БД решат эту проблему элегантнее.

2023-07-24 12:23 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +                .owner(UserMapper.fromUserDto(userService.getUserById(ownerId)))
Чем именно?

2023-07-24 12:24 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        return itemRepository.findAll().stream()
Это важно, как упражнение в оптимизации алгоритмов, и понимании того, как можно решать такие задачи

2023-07-24 12:25 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/repository/UserRepositoryImpl.java
> +        return entities.values().stream()
Как написал выше - это неплохое упражнение

2023-07-24 12:28 UTC, alexache approved these changes

2023-07-29 08:42 UTC, merged