feat: Sprint14
emtpy61/java-shareit pull request #2
Opened 2023-08-13 17:43 UTC by emtpy61

Sprint14

2023-08-14 19:10 UTC, alexache requested changes

2023-08-14 19:10 UTC, alexache commented on src/main/resources/application.properties
> +spring.config.activate.on-profile=test
Зачем это изменение? Стоит вернуть назад и проверить, что билд станет проходить

2023-08-15 09:17 UTC, emtpy61 commented on src/main/resources/application.properties
> +spring.config.activate.on-profile=test
Просто попытка. У людей в чате с этим были проблемы. Но проблема тут была с Mapstruct он не хотел перезаписывать уже сгенеренные файлы.

2023-08-16 05:38 UTC, alexache requested changes

2023-08-16 05:38 UTC, alexache commented on pom.xml
> +        <dependency>
ЧТо-то случилось с отступами в этом файле

2023-08-16 05:38 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
>  @Data
Эта аннотация не совместима с JPA моделью, потому что включает в себя @EqualsAndHashcode, который не учитывает специфику JPA

2023-08-16 05:38 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +    private BookingMapper bookingMapper;
Выбивается тем, что не final

2023-08-16 05:38 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/dto/ItemBookingDto.java
> +    Long id;
Пропущены модификаторы доступа

2023-08-16 05:38 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepository.java
> +    @Query("SELECT i FROM Item i "
(опционально) это тоже решаемо через именование метода с equalsIgnoreCase

2023-08-16 05:38 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/mapper/ItemMapper.java
> +    Item itemDtotoItem(ItemDto itemDto);
Более правильно будет itemDtoToItem, видимо опечатка

2023-08-16 05:38 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        item.getBookings().stream()
Как-то выглядит лишним для анализа в приложении, можно бы сделать частью запроса к базе - дай мне подтвержденное бронирование пользователя данной вещи, которое было завершено до текущего времени

2023-08-16 05:38 UTC, alexache commented on src/main/resources/application.yml
> +logging:
Выглядит как дублирование того, что в application.properties

2023-08-16 08:34 UTC, emtpy61 commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
>  @Data
Спасибо! Почитал про lombok в jpa. Поправил

2023-08-16 09:35 UTC, emtpy61 commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepository.java
> +    @Query("SELECT i FROM Item i "
Мне мой вариант нравится больше чем использование :
itemRepository.findByNameIgnoreCaseContainingOrDescriptionIgnoreCaseContainingAndAvailable(text,text,true);

2023-08-16 09:39 UTC, emtpy61 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +    private BookingMapper bookingMapper;
изза ошибок в pom работало только не с final. Поправил

2023-08-16 09:46 UTC, emtpy61 commented on src/main/java/ru/practicum/shareit/item/mapper/ItemMapper.java
> +    Item itemDtotoItem(ItemDto itemDto);
поправил

2023-08-16 09:47 UTC, emtpy61 commented on src/main/resources/application.yml
> +logging:
Без этого не показывал в идее sql запросы сгенеренные

2023-08-16 10:17 UTC, emtpy61 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        item.getBookings().stream()
поправил

2023-08-17 05:16 UTC, alexache approved these changes

2023-08-17 08:34 UTC, merged