sprint15
emtpy61/java-shareit pull request #3
Opened 2023-08-17 17:33 UTC by emtpy61

sprint15

2023-08-20 19:58 UTC, alexache requested changes

2023-08-20 19:58 UTC, alexache commented on pom.xml
> +                            <exclude>**/*BookingMapper*</exclude>
Эти исключения нужно бы убрать, нет оснований их делать таковыми

2023-08-20 19:58 UTC, alexache commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    MockMvc mvc;
Модификатор доступа у полей все же нужен

2023-08-20 19:58 UTC, alexache commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    }
Негативные сценарии с получением ошибки валидации тут тоже не помешает

2023-08-20 19:58 UTC, alexache commented on src/test/java/ru/practicum/shareit/item/ItemControllerTest.java
> +                .andExpect(content().json(objectMapper.writeValueAsString(itemDto)));
Не помешает verify(.., times(1) в большем количестве тест кейсов

2023-08-20 19:58 UTC, alexache commented on src/test/java/ru/practicum/shareit/item/dto/CreateCommentDtoTest.java
> +class CreateCommentDtoTest {
Что это за пустые классы?

2023-08-20 19:58 UTC, alexache commented on src/test/java/ru/practicum/shareit/item/service/ItemServiceTest.java
> +        ReflectionTestUtils.setField(itemService, "itemMapper", itemMapper);
С ходу как-то не уверен, что это правильный способ выставления мапперов. Рефлексия редко когда необходима

2023-08-20 19:58 UTC, alexache commented on src/test/java/ru/practicum/shareit/request/service/ItemRequestServiceTest.java
> +    }
Не хватает негативных сценариев

2023-08-21 15:18 UTC, emtpy61 commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    MockMvc mvc;
Поправил

2023-08-21 20:32 UTC, emtpy61 commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    }
добавил

2023-08-21 20:33 UTC, emtpy61 commented on src/test/java/ru/practicum/shareit/item/service/ItemServiceTest.java
> +        ReflectionTestUtils.setField(itemService, "itemMapper", itemMapper);
Иначе вложенные мапперы не подхватываются. Переписывать рабочий код на инжект вложенных мапперов через конструктор нет времени.

2023-08-21 20:48 UTC, emtpy61 commented on src/test/java/ru/practicum/shareit/item/ItemControllerTest.java
> +                .andExpect(content().json(objectMapper.writeValueAsString(itemDto)));
поправил

2023-08-21 22:29 UTC, emtpy61 commented on src/test/java/ru/practicum/shareit/item/dto/CreateCommentDtoTest.java
> +class CreateCommentDtoTest {
Забыл 🤦

2023-08-21 22:29 UTC, emtpy61 commented on src/test/java/ru/practicum/shareit/request/service/ItemRequestServiceTest.java
> +    }
добавил.

2023-08-21 23:24 UTC, emtpy61 commented on pom.xml
> +                            <exclude>**/*BookingMapper*</exclude>
Без них не проходит покрытие. Тестировать сгенерированный код кажется такое себе...

2023-08-22 05:33 UTC, alexache commented on pom.xml
> +                            <exclude>**/*BookingMapper*</exclude>
Специально тестить сгенерированный код - да, плохо, а вот если он протестирован через тестирование сервиса, то почему бы и не оставить

2023-08-22 05:49 UTC, alexache approved these changes

2023-08-22 05:49 UTC, alexache commented on src/test/java/ru/practicum/shareit/booking/service/BookingServiceTest.java
> +        when(userRepository.findById(anyLong())).thenReturn(Optional.of(booker));
Все эти айди, использованные для findById в разных местах, лучше задавать как есть, раз они известны, вместо anyLong() - booker.getId() и прочее

2023-08-22 06:09 UTC, merged