Add docker
emtpy61/java-shareit pull request #4
Opened 2023-08-26 00:04 UTC by emtpy61

2023-08-27 05:45 UTC, alexache requested changes

2023-08-27 05:45 UTC, alexache commented on gateway/src/main/java/ru/practicum/shareit/item/ItemClient.java
> +        Map<String, Object> parameters = Map.of(
Это мапа ведь не используется? И не имеет смысла, так как всего один элемент

2023-08-27 05:45 UTC, alexache commented on server/pom.xml
> +            <artifactId>spring-boot-starter-validation</artifactId>
У модуля сервиса не должно оставаться валидаций

2023-08-27 05:45 UTC, alexache commented on server/src/main/java/ru/practicum/shareit/item/dto/CreateCommentDto.java
> +    @NotBlank
В данном модуле не должно оставаться валидаций

2023-08-27 05:45 UTC, alexache commented on server/src/main/java/ru/practicum/shareit/item/dto/CreateItemDto.java
> +    @NotNull(message = "не может быть null.")
И этих валидаций

2023-08-27 13:46 UTC, emtpy61 commented on gateway/src/main/java/ru/practicum/shareit/item/ItemClient.java
> +        Map<String, Object> parameters = Map.of(
Да! Забыл убрать.
Убрал

2023-08-27 13:47 UTC, emtpy61 commented on server/src/main/java/ru/practicum/shareit/item/dto/CreateCommentDto.java
> +    @NotBlank
Убрал.

2023-08-27 13:47 UTC, emtpy61 commented on server/pom.xml
> +            <artifactId>spring-boot-starter-validation</artifactId>
Убрал.

2023-08-27 13:47 UTC, emtpy61 commented on server/src/main/java/ru/practicum/shareit/item/dto/CreateItemDto.java
> +    @NotNull(message = "не может быть null.")
Убрал.

2023-08-28 05:35 UTC, alexache approved these changes

2023-09-02 07:20 UTC, merged